name: Example Test Dataset

on:
  push:
  pull_request:

jobs:
  test-example-dataset:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Download LUCA.h5
        run: wget https://omabrowser.org/All/LUCA.h5

      - name: Run omamer search
        run: |
          mkdir output
          uv run omamer search \
            --db LUCA.h5 \
            --query example_data/UP000005640_9606.fasta \
            --out output/UP000005640_9606.omamer

      - name: Run omark
        run: |
          uv run omark \
            -f output/UP000005640_9606.omamer \
            -d LUCA.h5 \
            -o output/

      - name: Compare output with expected
        run: diff output/UP000005640_9606.sum example_data/UP000005640_9606.sum
